# AuthMeForm 配置文件
# 作者: 柠枺 (ning-g-mo)

# 基本设置
java_anvil_enabled: true       # 是否为Java版启用铁砧菜单
java_auto_login: false         # 是否为Java版启用自动登录

bedrock_form_enabled: true     # 是否为基岩版启用表单
bedrock_auto_login: false      # 是否为基岩版启用自动登录
bedrock_auto_register: false   # 是否为基岩版启用自动注册

# 会话设置
session_timeout: 1800000       # 会话超时时间（毫秒），默认30分钟

# 消息设置
messages:
  # 登录相关
  login_title: "&6登录"
  login_prompt: "&e请在此输入您的密码"
  login_message: "&a请在铁砧中输入您的密码来登录"
  login_success: "&a登录成功！"
  login_cancelled: "&c登录操作已取消，请重新尝试"
  
  # 注册相关
  register_title: "&6注册"
  register_prompt: "&e请在此设置您的密码"
  register_message: "&a请在铁砧中设置您的密码来注册"
  register_success: "&a注册成功！"
  register_cancelled: "&c注册操作已取消，请重新尝试"
  
  # 自动登录相关
  auto_login: "&a您已被自动登录！"
  auto_register: "&a您已被自动注册！密码为: &e%password%&a 请妥善保管"
  
  # 需要登录/注册的提示
  need_login: "&c请登录后再进行操作！使用 &f/login &c命令打开登录界面"
  need_register: "&c请注册后再进行操作！使用 &f/register &c命令打开注册界面"
  
  # 聊天登录相关
  chat_login_prompt: "&a请在聊天框中直接输入您的密码来登录"
  chat_register_prompt: "&a请在聊天框中直接输入您的密码来注册"
  login_failed: "&c密码错误，请重新输入"
  register_error: "&c注册失败，请重新尝试"
  login_error: "&c登录时出错，请重新尝试"
  
  # 密码命令相关
  password_command:
    success: "&a密码修改成功！"
    old_password_wrong: "&c旧密码错误！"
    too_short: "&c新密码太短，至少需要%min_length%个字符！"
    too_weak: "&c密码强度不足！请包含数字和特殊字符。"
    strength: "&7密码强度: %strength%"

# 安全设置
security:
  max_login_attempts: 5      # 最大登录尝试次数
  lockout_duration: 300000   # 锁定时间（毫秒），默认5分钟
  min_password_length: 6     # 密码最小长度
  enforce_password_strength: true  # 是否强制密码强度 