name: AuthMeForm
version: ${project.version}
main: cn.ningmo.authmeform.AuthMeForm
api-version: '1.18'
authors: [ning_mo]
description: 为AuthMe提供表单界面
website: https://github.com/ning-g-mo

depend: [AuthMe]
softdepend: [floodgate]

commands:
  authmeform:
    description: 插件主命令
    usage: /authmeform
    aliases: [amf]
  login:
    description: 打开登录/注册界面
    usage: /login
    aliases: [l, reg, register]

permissions:
  authmeform.use:
    description: 允许使用AuthMeForm基本命令
    default: true
  authmeform.admin:
    description: 允许使用AuthMeForm管理命令
    default: op 